### PR TITLE
Compiling on Windows Documentation

### PR DESCRIPTION
**Pull request by tempris**
Adds documentation page on how to compile in the Windows operating system using MSYS2.

### CODE REVIEW

**Comment by tempris** [comment]
Please postpone merging this branch until I verify this on a 64 bit system, had issues while testing on someone else's machine.

**Comment by qreeves** [comment]
Converting to draft.

**Comment by qreeves** [comment]
Hi, just checking in on the progress of this PR after six months.

**Comment by qreeves** [comment]
No response after 12 months, closing.

**Pull request closed without merging**
